- name: Install packages
  ansible.builtin.package:
    name:
      - strongswan
      - strongswan-pki
      - libcharon-extra-plugins
      - libcharon-extauth-plugins
      - libstrongswan-extra-plugins

- name: Strongswan ipsec.conf
  template:
    src: etc/ipsec.conf.j2
    dest: "/etc/ipsec.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ipsec restart

- name: Strongswan ipsec.secrets
  template:
    src: etc/ipsec.secrets.j2
    dest: "/etc/ipsec.secrets"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: ipsec secrets reload

# - name: Strongswan updown script
#   block:
#     - name: create strongswan directory
#       file:
#         path: "{{strongswan_prefix}}/strongswan"
#         state: directory
#         recurse: yes
#         owner: "root"
#         group: "root"

#     - name: add updown script
#       template:
#         src: strongswan/updown.sh.j2
#         dest: "{{ strongswan_prefix }}/strongswan/updown.sh"
#         owner: "root"
#         group: "root"
#         mode: "0755"
#       notify: ipsec restart
#   when: strongswan_updown is defined and strongswan_updown.keys()|length > 0

# - name: setup logfile
#   template:
#     src: strongswan/charon-logging.conf.j2
#     dest: /etc/strongswan.d/charon-logging.conf
#   notify: ipsec restart

# - name: disable routes installing by charon
#   replace:
#     path: /etc/strongswan.d/charon.conf
#     regexp: '^.*install_routes.*yes|^.*#.*install_routes.*'
#     replace: 'install_routes = no'
#   notify: ipsec restart
